### 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written Python code that provides functionalities for specific tasks or domains. These libraries contain modules, functions, and classes that developers can use to perform various tasks without having to write the code from scratch.

We use Python libraries for several reasons:

1. Code Reusability: Libraries contain pre-written code that can be reused across projects, saving time and effort for developers.

2. Increased Productivity: By leveraging existing libraries, developers can focus on implementing specific features or solving unique problems rather than spending time on common tasks.

3. Domain-specific Functionality: Python libraries are often specialized for specific domains such as data analysis, machine learning, web development, etc. Using these libraries allows developers to leverage the expertise and optimizations tailored for those domains.

4. Performance Optimization: Libraries are often optimized for performance, utilizing efficient algorithms and data structures, which can lead to faster execution of code.

5. Community Support and Collaboration: Python libraries are usually developed and maintained by a community of contributors. This allows developers to benefit from collective knowledge, bug fixes, and updates contributed by the community.

6. Overall, Python libraries are essential tools for Python developers as they enable them to build complex and powerful applications efficiently by leveraging existing solutions and community expertise.

### 2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of elements, but they have several differences:

1. Data Type: NumPy arrays are homogeneous, meaning they can only contain elements of the same data type (e.g., integers, floats, etc.). In contrast, Python lists can contain elements of different data types.

2. Memory Efficiency: NumPy arrays are more memory efficient than Python lists. This is because NumPy arrays are stored as contiguous blocks of memory, whereas Python lists are pointers to objects stored elsewhere in memory.

3. Performance: NumPy operations are typically faster than equivalent operations on Python lists, especially for large datasets. This is because NumPy arrays leverage vectorized operations and are implemented in C, which is more efficient than the Python interpreter.

4. Functionality: NumPy arrays offer a wide range of mathematical operations and functions optimized for numerical computations. They also support multi-dimensional arrays and broadcasting, which allows operations on arrays of different shapes. Python lists, on the other hand, have fewer built-in functionalities for numerical computations.

5. Ease of Use: Python lists are more versatile and easier to work with for general-purpose tasks due to their flexibility and built-in methods. NumPy arrays, while powerful for numerical computations, may require additional learning and understanding of array-oriented programming concepts.

In summary, NumPy arrays are preferable for numerical computations and large datasets due to their performance and memory efficiency, while Python lists are more versatile and easier to use for general-purpose tasks.

### 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
import numpy as np

# Creating the array
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

# Shape of the array
shape = arr.shape
print("Shape of the array is = ", shape)

# Size of the array
size = arr.size
print("Size of the array is = ", size)

# dimension of the array
dim = arr.ndim
print("Dimension of the array is = ", dim)

Shape of the array is =  (3, 4)
Size of the array is =  12
Dimension of the array is =  2


### 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
# creating the array
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# first row access

print("The first row of the array is  =", arr1[0])


The first row of the array is  = [1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [17]:
# Creating the array
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Accessing the element
print("The element at third row and fourth column is =", arr2[2][3])

The element at third row and fourth column is = 12


### 6. Write code to extract all odd -indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [19]:
# Creating the array
arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

# extracting the element
odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)

Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [29]:
# Generation of matrix

mat = np.random.rand(3,3)

print("The matrix is as below:")
print(mat)

The matrix is as below:
[[0.84968441 0.31679875 0.5764795 ]
 [0.9039552  0.48621852 0.18438854]
 [0.4713804  0.09381361 0.32514948]]


### 8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand and np.random.randn are both functions provided by the NumPy library for generating random numbers, but they differ in the way they generate these numbers and the distribution they follow.

1. np.random.rand: This function generates random numbers from a uniform distribution over the range [0, 1). It takes as input the dimensions of the output array. For example, if you specify the dimensions (2, 3), it will return a 2x3 array filled with random numbers between 0 and 1.


2. np.random.randn: This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). It also takes as input the dimensions of the output array. For example, if you specify the dimensions (2, 3), it will return a 2x3 array filled with random numbers following the standard normal distribution.

### 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [33]:
# Creating the array
arr4 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Expanding the dimensions
expand_arr = np.expand_dims(arr4, axis = 0)


print("The array after expanded dimension is:")
print(expand_arr)

The array after expanded dimension is:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


### 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [36]:
# Creating the array
arr5 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print("The original array is:")
print(arr5)
print('\n')
# Transposing the array
transpose_array = arr5.T

print("The array after transpose is :")
print(transpose_array)

The original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


The array after transpose is :
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consider the following matrix:
#### Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#### Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

#### Perform the following operation using Python1
1. Index wise multiplication
2. Matix multiplication
3. Add both the matrix
4. Subtact matix B from A
5. Divide Matrix B by A

In [38]:
# creating both the matrix

A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
B = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Index wise multiplication
ind_mul = A*B
print("The index wise multiplication of A with B is:")
print(ind_mul)

The index wise multiplication of A with B is:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


#### Matrix Multiplication is not possible for the given matrix as the number of column of matrix A is not equal to number of row in matrix B

In [40]:
# Addition of A and B

add_A_B = A+B
print("Addition of matrix A and B is:")
print(add_A_B)

Addition of matrix A and B is:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [41]:
# Subtract B from A
sub_B_A = B-A
print("Subtraction of B from A:")
print(sub_B_A)

Subtraction of B from A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [42]:
# Divide matrix B by A
div_B_A = B/A
print("Divsion of B by A results:")
print(div_B_A)

Divsion of B by A results:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, we can use the byteswap() function to swap the byte order of an array. This function swaps the byte order of the elements of the array in place.

In [45]:
import numpy as np

# Create an array
array = np.array([1, 256, 65536], dtype=np.int32)

# Swap byte order
swapped_array = array.byteswap()

print("Original array:")
print(array)
print('\n')

print("Swapped byte order array:")
print(swapped_array)


Original array:
[    1   256 65536]


Swapped byte order array:
[16777216    65536      256]


### 13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix. The significance of this function lies in its application in linear algebra, particularly in solving systems of linear equations and in various other mathematical computations.

Here are some key points regarding the significance of np.linalg.inv:

1. Solving Linear Equations: One of the primary applications of matrix inversion is in solving systems of linear equations of the form Ax = b, where A is a coefficient matrix, x is the vector of variables to be solved for, and b is the constant vector. If A is a square matrix, then the solution can be found using the equation x = A⁻¹b.

2. Matrix Division: In linear algebra, division of matrices is not defined. However, the concept of inverse matrices is analogous to division. If A is an invertible square matrix (i.e., its determinant is non-zero), then A⁻¹ represents the "inverse" of A, such that A⁻¹A = I, where I is the identity matrix.

3. Eigenvalue and Eigenvector Computations: Matrix inversion is also used in the computation of eigenvalues and eigenvectors. For a square matrix A, the eigenvalues λ and eigenvectors v satisfy the equation Av = λv. In some cases, solving for eigenvalues and eigenvectors involves computing the inverse of the matrix (A - λI), where I is the identity matrix.

4. Numerical Stability: In practical numerical computations, the direct computation of the inverse of a matrix can be numerically unstable, especially for matrices that are ill-conditioned (close to being singular). In such cases, alternative methods such as LU decomposition (via np.linalg.solve) are preferred for solving systems of equations.

### 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data. It allows you to reorganize the elements of an array into a new shape while maintaining the total number of elements.

Here's how np.reshape is used:

In [46]:
import numpy as np

# Create an array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Reshape the array to have 3 rows and 2 columns
reshaped_array = np.reshape(array, (3, 2))

print("Original array:")
print(array)
print("\nReshaped array:")
print(reshaped_array)

Original array:
[[1 2 3]
 [4 5 6]]

Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


### 15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined together in element-wise operations. This means that you can perform arithmetic operations, for example, on arrays of different shapes without having to explicitly reshape or tile them to match each other's shapes. Broadcasting effectively extends the element-wise operations to operate on arrays of different shapes by implicitly replicating the smaller array along the missing dimensions.